media:
  input: src/assets/images/posts
  output: src/assets/images/posts
content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/data/post
    filename: '{year}-{month}-{day}-{slug}.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: excerpt
        label: Excerpt
        type: string
      - name: publishDate
        label: Publish Dater
        type: date
        options:
          time: true
          format: dd-MM-yyyy HH:mm
        required: true
        
      - name: image
        label: Image
        type: image
      - name: tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [ pentesting,linux,privilege escalation,security,cheatsheet ]
      
      - name: category
        label: Category
        type: string
      - name: metadata
        label: Metadata
        type: object
        fields:
          - name: canonical
            label: Canonical URL
            type: string
      - name: body
        label: Body
        type: rich-text
        required: true
   