media:
  input: public/assets/images
  output: /assets/images
content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/data/post
    filename: '{year}-{month}-{day}-{slug}.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: excerpt
        label: Excerpt
        type: string
      - name: publishDate
        label: Publish Date
        type: date
        required: true
        
      - name: image
        label: Image
        type: image
      - name: tags
        label: Tags
        type: text
      
      - name: category
        label: Category
        type: string
      - name: metadata
        label: Metadata
        type: object
        fields:
          - name: canonical
            label: Canonical URL
            type: string
      - name: body
        label: Body
        type: rich-text
        required: true
   